# Generated by Django 2.2.6 on 2019-11-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.TextField(default='Sin direccion', max_length=50)),
                ('genero', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='Femenino', max_length=15)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], default='Soltero', max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaApertura', models.DateField(auto_now_add=True)),
                ('tipoCuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro')], default='Ahorro', max_length=30)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=160)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Cuenta')),
            ],
        ),
    ]
